# Generated by Django 4.2.7 on 2025-11-06 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('daily_return', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('moving_avg_7', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('week_52_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('week_52_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volatility_score', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('momentum', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.company')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('company', 'date')},
            },
        ),
    ]
